# syntax=docker/dockerfile:1

# ── PowerFox / Techno Store — production Docker image ─────────────────────
# Multi-stage build: install deps -> build (Next.js standalone output) ->
# minimal runtime image. Migrations/seeding are run separately (see
# docker-compose.yml / README), this image only serves the app.

FROM node:22-alpine AS base
RUN corepack enable

# ── deps: install with pnpm, cached separately from source changes ────────
FROM base AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# ── builder: full source + build (needs devDependencies + build-time env) ─
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time only placeholders so `next build` can statically analyze pages
# that read env vars; real secrets are injected at runtime (see compose).
ENV NEXT_TELEMETRY_DISABLED=1 \
    DATABASE_URL="postgres://placeholder:placeholder@localhost:5432/placeholder" \
    BETTER_AUTH_SECRET="build-time-placeholder-not-used-at-runtime" \
    BETTER_AUTH_URL="http://localhost:3000"

RUN pnpm build

# ── runner: minimal runtime, only the standalone server + static assets ───
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Local upload fallback (used when BLOB_READ_WRITE_TOKEN is not set, i.e. every
# self-hosted/Docker deployment): the nextjs user needs write access here, and
# docker-compose mounts a named volume on this path so uploaded product photos
# survive container restarts/rebuilds.
RUN mkdir -p ./public/uploads/products && chown -R nextjs:nodejs ./public/uploads

# db/ + scripts/ are needed for one-off setup commands (db-setup.mjs applies
# db/schema.sql + db/seed.sql via the `pg` driver — already a prod dependency,
# no drizzle-kit/devDependencies needed at runtime).
COPY --from=builder --chown=nextjs:nodejs /app/scripts ./scripts
COPY --from=builder --chown=nextjs:nodejs /app/db ./db
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json

USER nextjs
EXPOSE 3000

# server.js is generated by Next's standalone output.
CMD ["node", "server.js"]
