defaults.url=https://de.sentry.io/
defaults.org=hfdzah
defaults.project=sentry-chestnut-leaf
# Vercel Sentry integration: npx @sentry/wizard@latest -i nextjs --saas --org hfdzah --project sentry-chestnut-leaf --coming-from vercel
