/**
 * Standalone PostgreSQL dump utility.
 *
 * Produces a single self-contained `db/dump.sql` file (schema + data) that can
 * be restored into any local PostgreSQL instance with:
 *
 *     createdb myshop
 *     psql myshop -f db/dump.sql
 *
 * It does not rely on `pg_dump` (which isn't available in this environment).
 * Instead it reconstructs DDL from the system catalogs and emits data as
 * INSERT statements, letting PostgreSQL itself format every value via
 * `col::text` + `quote_nullable(...)` so all types (jsonb, arrays, timestamps,
 * numerics, booleans) round-trip correctly.
 *
 * Restore order is chosen to avoid dependency problems:
 *   1. CREATE SEQUENCE (all)
 *   2. CREATE TABLE (columns + defaults + NOT NULL + PRIMARY KEY inline)
 *   3. Data INSERTs
 *   4. SELECT setval(...) to restore sequence positions
 *   5. ALTER TABLE ADD CONSTRAINT (unique / foreign key / check)
 *   6. CREATE INDEX (remaining non-constraint indexes)
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import pg from 'pg'

function cleanConnString(raw) {
  // Neon pooled URLs carry sslmode/channel_binding params that the `pg` driver
  // does not understand; strip them and rely on explicit ssl options instead.
  return raw.replace(/[?&](sslmode|channel_binding)=[^&]*/gi, '').replace(/[?&]+$/, '')
}

const q = (id) => '"' + id.replace(/"/g, '""') + '"'

async function main() {
  const url = process.env.DATABASE_URL
  if (!url) throw new Error('DATABASE_URL is not set')
  const pool = new pg.Pool({ connectionString: cleanConnString(url), ssl: { rejectUnauthorized: false } })
  // Pooled connections (e.g. Neon pgbouncer) can arrive with a stale
  // search_path from a previous session — pin it so unqualified table
  // names always resolve to the public schema.
  pool.on('connect', (client) => client.query('set search_path to public'))

  const out = []
  out.push('--')
  out.push('-- Database dump generated by scripts/dump-db.mjs')
  out.push('-- Generated: ' + new Date().toISOString())
  out.push('-- Restore:  createdb myshop && psql myshop -f db/dump.sql')
  out.push('--')
  out.push('')
  out.push('SET client_encoding = ' + "'UTF8'" + ';')
  out.push('SET standard_conforming_strings = on;')
  out.push('SET check_function_bodies = false;')
  out.push('SET client_min_messages = warning;')
  out.push('')

  // ---- Tables ----
  const { rows: tableRows } = await pool.query(
    `select tablename from pg_tables where schemaname='public' order by tablename`,
  )
  const tables = tableRows.map((r) => r.tablename)

  // ---- Sequences ----
  const { rows: seqRows } = await pool.query(
    `select sequencename from pg_sequences where schemaname='public' order by sequencename`,
  )

  out.push('-- ============================================================')
  out.push('-- Sequences')
  out.push('-- ============================================================')
  for (const s of seqRows) {
    out.push(`CREATE SEQUENCE IF NOT EXISTS ${q(s.sequencename)};`)
  }
  out.push('')

  // ---- Table DDL ----
  out.push('-- ============================================================')
  out.push('-- Tables')
  out.push('-- ============================================================')
  for (const table of tables) {
    const { rows: cols } = await pool.query(
      `select a.attname as name,
              format_type(a.atttypid, a.atttypmod) as type,
              a.attnotnull as notnull,
              pg_get_expr(d.adbin, d.adrelid) as default_expr
         from pg_attribute a
         left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
        where a.attrelid = ('public.' || quote_ident($1))::regclass
          and a.attnum > 0
          and not a.attisdropped
        order by a.attnum`,
      [table],
    )

    // Inline PRIMARY KEY (safe to create before data; other constraints added later).
    const { rows: pk } = await pool.query(
      `select pg_get_constraintdef(c.oid) as def
         from pg_constraint c
        where c.conrelid = ('public.' || quote_ident($1))::regclass
          and c.contype = 'p'`,
      [table],
    )

    const lines = cols.map((c) => {
      let line = `  ${q(c.name)} ${c.type}`
      if (c.default_expr) line += ` DEFAULT ${c.default_expr}`
      if (c.notnull) line += ' NOT NULL'
      return line
    })
    if (pk.length) lines.push(`  ${pk[0].def}`)

    out.push(`CREATE TABLE ${q(table)} (`)
    out.push(lines.join(',\n'))
    out.push(');')
    out.push('')
  }

  // ---- Data ----
  out.push('-- ============================================================')
  out.push('-- Data')
  out.push('-- ============================================================')
  for (const table of tables) {
    const { rows: cols } = await pool.query(
      `select a.attname as name
         from pg_attribute a
        where a.attrelid = ('public.' || quote_ident($1))::regclass
          and a.attnum > 0 and not a.attisdropped
        order by a.attnum`,
      [table],
    )
    if (!cols.length) continue
    const colList = cols.map((c) => q(c.name)).join(', ')
    // Build a server-side expression that emits a ready-to-run INSERT per row.
    const valueExpr = cols
      .map((c) => `quote_nullable(${q(c.name)}::text)`)
      .join(" || ',' || ")
    const sql =
      `select 'INSERT INTO ${q(table)} (${colList}) VALUES (' || ${valueExpr} || ');' as line ` +
      `from ${q(table)}`
    const { rows } = await pool.query(sql)
    if (rows.length) {
      out.push(`-- ${table} (${rows.length} rows)`)
      for (const r of rows) out.push(r.line)
      out.push('')
    }
  }

  // ---- Sequence values ----
  out.push('-- ============================================================')
  out.push('-- Sequence values')
  out.push('-- ============================================================')
  for (const s of seqRows) {
    const { rows } = await pool.query(`select last_value, is_called from ${q(s.sequencename)}`)
    if (rows.length) {
      const { last_value, is_called } = rows[0]
      out.push(`SELECT setval('${s.sequencename.replace(/'/g, "''")}', ${last_value}, ${is_called});`)
    }
  }
  out.push('')

  // ---- Constraints (unique / foreign key / check), added after data ----
  out.push('-- ============================================================')
  out.push('-- Constraints (unique, foreign key, check)')
  out.push('-- ============================================================')
  const { rows: cons } = await pool.query(
    `select rel.relname as table, c.conname as name, pg_get_constraintdef(c.oid) as def, c.contype
       from pg_constraint c
       join pg_class rel on rel.oid = c.conrelid
       join pg_namespace n on n.oid = rel.relnamespace
      where n.nspname = 'public' and c.contype in ('u','f','c')
      order by c.contype, rel.relname, c.conname`,
  )
  for (const c of cons) {
    out.push(`ALTER TABLE ${q(c.table)} ADD CONSTRAINT ${q(c.name)} ${c.def};`)
  }
  out.push('')

  // ---- Indexes (skip those backing a constraint) ----
  out.push('-- ============================================================')
  out.push('-- Indexes')
  out.push('-- ============================================================')
  const { rows: idx } = await pool.query(
    `select i.indexname, i.indexdef
       from pg_indexes i
      where i.schemaname = 'public'
        and not exists (
          select 1 from pg_constraint c
          where c.conindid = (quote_ident(i.schemaname) || '.' || quote_ident(i.indexname))::regclass
        )
      order by i.tablename, i.indexname`,
  )
  for (const r of idx) out.push(r.indexdef + ';')
  out.push('')

  mkdirSync('db', { recursive: true })
  writeFileSync('db/dump.sql', out.join('\n'), 'utf8')

  const bytes = Buffer.byteLength(out.join('\n'))
  console.log(`[dump] wrote db/dump.sql — ${tables.length} tables, ${seqRows.length} sequences, ${(bytes / 1024).toFixed(1)} KB`)

  await pool.end()
}

main().catch((e) => {
  console.error('[dump] failed:', e.message)
  process.exit(1)
})
